import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalNav from "@/app/GlobalNav";
import AddressBar from "@/app/ui/AddressBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-scroll`}>
        <div className="grid [grid-template-columns:1fr_minmax(auto,240px)_min(1000px,100%)_1fr] gap-x-8 py-8">
          {/* Sidebar */}
          <div className="col-start-2">
            <GlobalNav />
          </div>

          {/* Main content */}
          <div className="col-start-3 space-y-6">
            <AddressBar />

            <div className="rounded-xl border border-zinc-800 p-8">
              {children}
            </div>
          </div>

          {/* Extra column content */}
          <div className="col-start-3 col-end-4 mt-28 flex items-center justify-center">
            {/* Add content here if needed */}
          </div>
        </div>
      </body>
    </html>
  );
}
